spring.application.name=demo

# DB 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=hoseo12!@

# JPA 설정 (엔티티를 통해 테이블을 자동 생성해주는 옵션)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true